# Generated by Django 5.1.7 on 2025-04-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_chat_interest_rabble_user_bio_user_follows_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommentLikes",
            new_name="CommentLike",
        ),
        migrations.RenameModel(
            old_name="PostLikes",
            new_name="PostLike",
        ),
    ]
