# Generated by Django 5.1.7 on 2025-04-16 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="chat",
            new_name="chat_id",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="subrabble",
            old_name="community_id",
            new_name="subrabble_community_id",
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("user_id", "chat_id")},
        ),
        migrations.RemoveField(
            model_name="message",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
