# Generated by Django 5.1.7 on 2025-04-23 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0004_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rabble",
            name="chat_id",
        ),
        migrations.RemoveField(
            model_name="rabble",
            name="subrabble_id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_comments",
                through="rabble.CommentLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="rabble.comment",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_posts",
                through="rabble.PostLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="added_to_chat",
            field=models.ManyToManyField(blank=True, to="rabble.chat"),
        ),
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interested_in",
            field=models.ManyToManyField(blank=True, to="rabble.interest"),
        ),
        migrations.AlterField(
            model_name="user",
            name="invites",
            field=models.ManyToManyField(
                blank=True, related_name="invitations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_rabbles",
            field=models.ManyToManyField(blank=True, to="rabble.rabble"),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_subrabbles",
            field=models.ManyToManyField(blank=True, to="rabble.subrabble"),
        ),
    ]
