# Generated by Django 5.1.7 on 2025-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0006_rabble_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subrabble",
            old_name="privacy",
            new_name="private",
        ),
        migrations.AddField(
            model_name="subrabble",
            name="subrabble_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="subrabble_community_id",
            field=models.TextField(unique=True),
        ),
    ]
