# Generated by Django 5.1.7 on 2025-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0007_subrabble_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(default="default_title"),
            preserve_default=False,
        ),
    ]
