# Generated by Django 5.1.7 on 2025-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0008_post_requires_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="subrabble_community_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
