# Generated by Django 5.1.7 on 2025-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0009_char_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="is_dislike",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="is_dislike",
            field=models.BooleanField(default=False),
        ),
    ]
