# Generated by Django 5.1.7 on 2025-05-13 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0011_subrabble_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="joined_subrabbles",
        ),
        migrations.AddField(
            model_name="subrabble",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_subrabbles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
