# Generated by Django 5.1.7 on 2025-05-13 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0012_remove_user_joined_subrabbles_subrabble_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="joined_rabbles",
        ),
        migrations.AddField(
            model_name="rabble",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_rabbles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
