# Generated by Django 5.1.7 on 2025-06-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0013_remove_user_joined_rabbles_rabble_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="rabble",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rabble",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
