# Generated by Django 5.1.7 on 2025-06-13 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0016_alter_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("contradicts", "Contradicts"),
                            ("supports", "Supports"),
                            ("elaborates", "Elaborates On"),
                            ("questions", "Questions"),
                            ("shifts_focus", "Shifts Focus"),
                            ("none", "None of Above"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="rabble.post",
                    ),
                ),
                (
                    "target_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="rabble.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("source_post", "target_post")},
            },
        ),
    ]
