# Generated by Django 5.1.7 on 2025-06-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0017_postrelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("contradicts", "Contradicts"),
                    ("supports", "Supports"),
                    ("elaborates", "Elaborates"),
                    ("questions", "Questions"),
                    ("transitions", "Transitions"),
                    ("none", "None"),
                ],
                max_length=20,
            ),
        ),
    ]
