name: CI
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create .env file
        working-directory: src/
        run: |
          echo "SECRET_KEY=dummy-key-for-ci" > .env
          echo "DEBUG=True" >> .env
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Check Django setup
        working-directory: src/
        run: python3 manage.py check

      - name: Run tests
        working-directory: src/
        run: pytest -v
